title: Aidan Fitzgerald
description: Computer Science, Cornell Engineering Class of 2020

# Imports from https://github.com/pages-themes/architect. We're gonna customize it.
# theme: jekyll-theme-architect

github:
  is_project_page: false

copyright:
  pub_year: 2017
  author: Aidan Fitzgerald
  license: null # gonna use this field to support a Creative Commons license
